### ISSUE TITLE
Publish for 2.12.0-M2?

### ISSUE THREAD

**Issue by andrewdbate** [nativelibs4java/scalaxy-streams#10]
Would it be possible to publish to Sonatype snapshots a version for 2.12.0-M2?

**Comment by ochafik** [comment]
Looks like there are [a couple of interesting failures](https://travis-ci.org/nativelibs4java/scalaxy-streams/jobs/83686188) with that milestone, to be investigated / fixed before we publish snapshots.

**Comment by andrewdbate** [comment]
Thanks so much for the speediness -- I'll try it now.

**Comment by ochafik** [comment]
Hey @andrewdbate, no worries, please just [give it a couple of minutes](https://travis-ci.org/nativelibs4java/scalaxy-streams/jobs/83719627) (snapshots are auto published on green builds from master branch).
