### ISSUE TITLE
Feature request: Ability to disable [info] logging

### ISSUE THREAD

**Issue by andrewdbate** [nativelibs4java/scalaxy-streams#6]
At the moment, Scalaxy prints to the info log for each optimization, such as:

```
E:\SourceCode\CR\module-a\src\main\scala\packagename\Class.scala:293: [Scalaxy] Optimized stream Range.map -> IndexedSeq (strategy: safe)
```

In a large project, this can cause pages of [info] lines to be printed in the SBT REPL, and error messages will go off the top of the screen because of the number of subsequent [info] lines.

Would it be possible to have an option to turn this off for Scalaxy?

**Comment by andrewdbate** [comment]
I don't mind submitting a pull request for this.

I would like to reduce the amount of `[info]`s that are printed to the SBT REPL because:
1.  I only do local surgery anyway, so I know what I'm doing when I apply the macro, and
2.  with all of the infos being printed, I might actually miss something important.

In `scalaxy.streams.StreamTransforms`, an an `if` could be added before

``` scala
info(tree.pos,
     Optimizations.optimizedStreamMessage(stream.describe(), strategy),
     force = flags.verbose)
```

such as 

``` scala
if (!quiet)
    info(tree.pos,
         Optimizations.optimizedStreamMessage(stream.describe(), strategy),
         force = flags.verbose)
```

and add another flag to `scalaxy.streams.flags` that corresponds to the property `scalaxy.streams.quiet`. What do you think?

**Comment by ochafik** [comment]
Good suggestion! (I'm still paranoid about displaying what happens, sorry for the noise!)

Implementation-wise I'd rather introduce some log-level abstraction, though, as there's currently already an appalling amount of debug/verbose/whatnot vars that need cleanup (prepping something up now).

**Comment by ochafik** [comment]
The latest snapshot should support `SCALAXY_STREAMS_QUIET=1` / `-Dscalaxy.streams.quiet=true`. 
Thanks for the suggestion and please let me know of any issue :-)

**Comment by andrewdbate** [comment]
The only way that I've found to add this to the SBT build script itself is to use:

```
initialize ~= { _ =>
  System.setProperty("scalaxy.streams.quiet", "true")
}
```

unless a full configuration with a `.scala` file is used, in which case you can just use `System.setProperty("scalaxy.streams.quiet", "true")` directly.

Do you know of any other or better way?

**Comment by ochafik** [comment]
An alternative would be to `export SCALAXY_STREAMS_QUIET=1` in your `~/.bashrc` / `~/.profile` (and in your project's `.travis.yml` file if needed), if you don't mind using the same setting everywhere.

The last (many) time(s) I checked, compiler plugin arguments were broken / impossible to use, not sure if that has changed but it would clearly provide for a better experience (wouldn't help with the macro case, though).

**Comment by ochafik** [comment]
(I might steal your snippet to put it in the readme soon, mind you ;-))

**Comment by pocorall** [comment]
+1 for this feature request. It is really annoying.
